### ISSUE TITLE
Remove old branches

### ISSUE THREAD

**Issue by tomowind** [garlicbulb-puzhuo/ggo#48]
As soon as possible...

@garlicbulb-puzhuo @garlicbulbxian @oakcreek We're all assignees for this one. Let's do this soon.

**Comment by tomowind** [comment]
We have only 5 branches to remove!

**Comment by oakcreek** [comment]
How can I find which old branches belong to me?

**Comment by tomowind** [comment]
See all branches here: https://github.com/garlicbulb-puzhuo/ggo/branches

**Comment by tomowind** [comment]
[20170222](https://github.com/garlicbulb-puzhuo/ggo/tree/20170222) is the only old branch. Yay! 

I will work on this one soon, and will get it reviewed by @oakcreek.
