### ISSUE TITLE
Change the setting not to accept a direct push to master

### ISSUE THREAD

**Issue by tomowind** [garlicbulb-puzhuo/ggo#71]
@garlicbulbxian This is your issue.

I could somehow pushed to origin/master using GitHub Desktop. I tried `git reset --hard` and `git push origin HEAD -f`, but it didn't work. Anyways, I pushed another commit after doing `git revert <commit>`. Try to find a setting, and change not to accept any direct push to master.

See my commits:
https://github.com/garlicbulb-puzhuo/ggo/commit/53dfc2d835ad11717f64ae4e42e0c4357fae7b39
https://github.com/garlicbulb-puzhuo/ggo/commit/42ae42eb917b61507a93529c6767c0bf5cfa67b9

**Comment by tomowind** [comment]
Go to setting of this repository.

Go to Branches.

Go to Protected Branches, add master.

Check protect this branch.

Check Require pull request reviews before merging.

Check Include administrators.

Don't check Require status checks to pass before merging, but we will have to work on this later.

**Comment by garlicbulbxian** [comment]
I changed the settings for the project to disallow direct push.
